name: Bug report
description: Report a bug or regression in Vidora
labels:
  - bug
  - needs-triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out a bug report!

        Please search existing issues first to avoid duplicates.

  - type: input
    id: summary
    attributes:
      label: Bug summary
      description: Short description of the problem.
      placeholder: e.g. "Download fails with error on Linux when using playlist URL"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: Steps to reproduce
      description: 'What did you do? List the exact steps so we can reproduce the issue.'
      placeholder: |
        1. Open Vidora
        2. Go to ...
        3. Click ...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual_behavior
    attributes:
      label: Actual behavior
      description: What actually happened? Include full error messages if possible.
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: OS / Platform
      description: Which platform(s) are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS (Intel)
        - macOS (Apple Silicon)
        - Linux
    validations:
      required: true

  - type: input
    id: vidora_version
    attributes:
      label: Vidora version
      description: Version number from the app (Settings → About) or the release tag.
      placeholder: e.g. 1.0.0
    validations:
      required: true

  - type: input
    id: node_version
    attributes:
      label: Node.js version (optional)
      description: Only if relevant or known.
      placeholder: e.g. 20.11.1

  - type: textarea
    id: logs
    attributes:
      label: Logs / Screenshots
      description: Attach logs, error messages, or screenshots that help explain the issue.
      render: shell

  - type: textarea
    id: additional_context
    attributes:
      label: Additional context
      description: Any other context about the problem.
